baseURL = "http://goodshepherdlynchburg.com/"
languageCode = "en-us"
title = "Church of the Good Shepherd"
theme = "alpha-church"
#themesDir = "../.."

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Who We Are"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "Who We Are"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "Who We Are"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Ministries"
    url = "/ministries"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Church of the Good Shepherd"
  subtitle = "A Community Walking In The Way Of Jesus"
  author = "COGS"
  keywords = ["church", "good", "shepherd"]
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp

  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  customCSS = ["example.css"]

  [params.banner]
    image = "img/church3.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "37.41293"
    longitude = "-79.14078"
    zoom = "19"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or else users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    service = "formspree"
    confirm_page = "/contact_thanks"
    # formspree_email=""


    [params.footer]
      copyright = ["Church of the Good Shepherd, 2021",]


    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

